### ISSUE TITLE
Infura error

### ISSUE THREAD

**Issue by MoriZalev** [hexoul/ether-stealer#3]
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0x9Faec63A9D4844cE4FAD2c25Bd1D8C232f466247>.
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0x043a991aae47d2CfeF327BE4D0A9f18b64f0C522>.
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0x0709729be896f636e92BAEB1c977aecB3809a418>.
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0x171e26Fe1Be15DC55391ae91E7Ae231662E09e57>.
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0x18dDA1aA269C2218989C6D8e7CdE515766bC8ce6>.
infura: error occurred. <invalid character 'i' looking for beginning of value>
FAILED attempt for address <0xc1be92E7dadCe21f632B9cAeAeB76Ec5d366a45C>.

**Comment by hexoul** [comment]
The errors are caused by wrong Infura API key. Did you set valid API key from https://docs.infura.io/infura/getting-started?
1. Create a project with Web3 network.
2. Use API KEY SECRET in SECURITY tab.
![image](https://user-images.githubusercontent.com/11401808/189511601-a968af03-30f4-458b-a67e-8ec339330e11.png)

**Comment by hexoul** [comment]
If you still have a problem, please reopen the issue.
